---
apiVersion: v1
kind: Pod 
meatadata:
  name: example3
  labels: 
    app: web
    purpose: multi-container
spec:
  - name: nginx
    image: nginx:latest
    ports:
    - name: tomcat
      image: tomcat:latest 
  
