---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: ngnix-ReplicaSet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template: 
    metadata:
      Lables:
        app: web
    spec:
      containers:
        - name: ngnix
          image: ngnix:latest
