---
apiVersion: v1
kind: Pod
metadata:
  name: burstable
  labels:
    app: httpd
    purpose: learning
    env: dev
spec:
  containers:
    - name: httpd
      image: httpd:latest
      resources:
        requests:
          cpu: 100M
          memory: 64Mi
        limits:
          cpu: 500M
          memory: 256Mi
      ports:
        - name: httpd
          protocol: TCP
          containerPort: 80